# Generated by Django 3.0.3 on 2020-04-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
