# Generated by Django 3.0.3 on 2020-04-09 20:18

from django.db import migrations, models
import django.db.models.deletion
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20200409_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='coach',
            name='email',
            field=models.EmailField(default='x.x@esprit.tn', max_length=254, validators=[hub.models.is_esprit_email], verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='coach',
            name='firstName',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='coach',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='lastName',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='Prenom'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_cred', to='hub.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='x.x@esprit.tn', max_length=254, validators=[hub.models.is_esprit_email], verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='Prenom'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_cred', to='hub.User'),
        ),
    ]
