# Generated by Django 3.0.3 on 2020-04-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20200409_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
